### ISSUE TITLE
Occasional 'Segmentation fault' on `enif_release_binary`

### ISSUE THREAD

**Issue by danilagamma** [urbanserj/cbase64-erlang-nif#3]
Sometimes library segfaults on bad base64 data:

How to reproduce:

``` erlang
Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V5.10.4  (abort with ^G)
1>  cbase64:decode(<<"{abc">>).
<<"ý¦Ü">>
2>  cbase64:decode(<<"{abc}">>).
** exception error: bad argument
     in function  cbase64:nif_decode/3
        called as cbase64:nif_decode(<<"{abc}">>,undefined,0)
     in call from cbase64:decode/3 (src/cbase64.erl, line 65)
3>  cbase64:decode(<<"{abc">>). 
<<"ý¦Ü">>
4>  cbase64:decode(<<"{abc}">>).
Segmentation fault
```

**Comment by urbanserj** [comment]
Thank you for the report!

I have fixed this issue in 461e3af249e4914fadf2d0681be25405f46cebf8. To avoid segfaults a proper test for `decode/1` function was added in dfed91c4847b796a4b323915c94db31ecdf8f12b.

It became 0.3.0 release.

**Comment by danilagamma** [comment]
Thank you for the fix! 
Too bad we're still sitting on `R16B03-1` and can't use `enif_schedule_nif` :(

**Comment by urbanserj** [comment]
I've backported patches to [support-r16](https://github.com/urbanserj/cbase64-erlang-nif/tree/support-r16) branch.
